// frontend-react/src/components/TodoItem.js
import React from 'react';


const TodoItem = ({ todo, onToggle, onEdit, onDelete }) => {
  const formatDate = (dateString) => {
    const options = { year: 'numeric', month: 'short', day: 'numeric' };
    return new Date(dateString).toLocaleDateString('es-ES', options);
  };


  return (
    <div className={`todo-item ${todo.completada ? 'completed' : ''}`}>
      <div className="todo-content">
        <div className="todo-header">
          <h3>{todo.titulo}</h3>
          <span className="todo-date">{formatDate(todo.fecha)}</span>
        </div>
        <p className="todo-description">{todo.contenido}</p>
        <div className="todo-status">
          {todo.completada ? (
            <span className="badge badge-completed">Completada</span>
          ) : (
            <span className="badge badge-pending">Pendiente</span>
          )}
        </div>
      </div>
     
      <div className="todo-actions">
        <button
          onClick={() => onToggle(todo._id)}
          className={`btn ${todo.completada ? 'btn-warning' : 'btn-success'}`}
          title={todo.completada ? 'Marcar como pendiente' : 'Marcar como completada'}
        >
          {todo.completada ? '↺' : '✓'}
        </button>
        <button
          onClick={() => onEdit(todo)}
          className="btn btn-info"
          title="Editar tarea"
        >
          ✎
        </button>
        <button
          onClick={() => onDelete(todo._id)}
          className="btn btn-danger"
          title="Eliminar tarea"
        >
          ×
        </button>
      </div>
    </div>
  );
};


export default TodoItem;

// frontend-vue/src/components/TodoItem.vue
<template>
  <div :class="['todo-item', { completed: todo.completada }]">
    <div class="todo-content">
      <div class="todo-header">
        <h3>{{ todo.titulo }}</h3>
        <span class="todo-date">{{ formatDate(todo.fecha) }}</span>
      </div>
      <p class="todo-description">{{ todo.contenido }}</p>
      <div class="todo-status">
        <span v-if="todo.completada" class="badge badge-completed">Completada</span>
        <span v-else class="badge badge-pending">Pendiente</span>
      </div>
    </div>
    
    <div class="todo-actions">
      <button
        @click="$emit('toggle', todo._id)"
        :class="['btn', todo.completada ? 'btn-warning' : 'btn-success']"
        :title="todo.completada ? 'Marcar como pendiente' : 'Marcar como completada'"
      >
        {{ todo.completada ? '↺' : '✓' }}
      </button>
      <button
        @click="$emit('edit', todo)"
        class="btn btn-info"
        title="Editar tarea"
      >
        ✎
      </button>
      <button
        @click="$emit('delete', todo._id)"
        class="btn btn-danger"
        title="Eliminar tarea"
      >
        ×
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    todo: {
      type: Object,
      required: true
    }
  },
  methods: {
    formatDate(dateString) {
      const options = { year: 'numeric', month: 'short', day: 'numeric' };
      return new Date(dateString).toLocaleDateString('es-ES', options);
    }
  }
};
</script>
