// frontend-vue/src/App.vue
<template>
  <div class="App">
    <header class="app-header">
      <h1>To-Do List</h1>
      <p class="subtitle">Gestiona tus tareas de manera eficiente</p>
    </header>

    <main class="app-main">
      <div v-if="error" class="error-message">
        {{ error }}
      </div>

      <div class="container">
        <TodoForm
          :editingTodo="editingTodo"
          @submit="handleSubmit"
          @cancel="handleCancelEdit"
        />

        <div v-if="loading" class="loading">
          Cargando tareas...
        </div>
        <TodoList
          v-else
          :todos="todos"
          @toggle="handleToggleTodo"
          @edit="handleEditTodo"
          @delete="handleDeleteTodo"
        />
      </div>
    </main>

    <footer class="app-footer">
      <p>Desarrollado por Joan Martínez | Vue.js + Node.js + MongoDB</p>
    </footer>
  </div>
</template>

<script>
import TodoForm from './components/TodoForm.vue';
import TodoList from './components/TodoList.vue';
import todoService from './services/todoService';

export default {
  name: 'App',
  components: {
    TodoForm,
    TodoList
  },
  data() {
    return {
      todos: [],
      editingTodo: null,
      loading: true,
      error: null
    };
  },
  mounted() {
    this.loadTodos();
  },
  methods: {
    async loadTodos() {
      try {
        this.loading = true;
        this.error = null;
        const response = await todoService.getAllTodos();
        this.todos = response.data;
      } catch (err) {
        this.error = 'Error al cargar las tareas. Verifica que el servidor esté corriendo.';
        console.error('Error:', err);
      } finally {
        this.loading = false;
      }
    },

    async handleCreateTodo(todoData) {
      try {
        const response = await todoService.createTodo(todoData);
        this.todos = [response.data, ...this.todos];
      } catch (err) {
        console.error('Error:', err);
      }
    },

    async handleUpdateTodo(todoData) {
      try {
        const response = await todoService.updateTodo(this.editingTodo._id, todoData);
        this.todos = this.todos.map(todo =>
          todo._id === this.editingTodo._id ? response.data : todo
        );
        this.editingTodo = null;
      } catch (err) {
        console.error('Error:', err);
      }
    },

    async handleToggleTodo(id) {
      try {
        const response = await todoService.toggleTodo(id);
        this.todos = this.todos.map(todo =>
          todo._id === id ? response.data : todo
        );
      } catch (err) {
        console.error('Error:', err);
      }
    },

    async handleDeleteTodo(id) {
      if (confirm('¿Estás seguro de que deseas eliminar esta tarea?')) {
        try {
          await todoService.deleteTodo(id);
          this.todos = this.todos.filter(todo => todo._id !== id);
        } catch (err) {
          console.error('Error:', err);
        }
      }
    },

    handleEditTodo(todo) {
      this.editingTodo = todo;
      window.scrollTo({ top: 0, behavior: 'smooth' });
    },

    handleCancelEdit() {
      this.editingTodo = null;
    },

    handleSubmit(todoData) {
      if (this.editingTodo) {
        this.handleUpdateTodo(todoData);
      } else {
        this.handleCreateTodo(todoData);
      }
    }
  }
};
</script>

// frontend-react/src/App.js
import React, { useState, useEffect } from 'react';
import TodoForm from './components/TodoForm';
import TodoList from './components/TodoList';
import todoService from './services/todoService';
import './App.css';

function App() {
  const [todos, setTodos] = useState([]);
  const [editingTodo, setEditingTodo] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Cargar tareas al iniciar
  useEffect(() => {
    loadTodos();
  }, []);

  const loadTodos = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await todoService.getAllTodos();
      setTodos(response.data);
    } catch (err) {
      setError('Error al cargar las tareas. Verifica que el servidor esté corriendo.');
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateTodo = async (todoData) => {
    try {
      const response = await todoService.createTodo(todoData);
      setTodos([response.data, ...todos]);
    } catch (err) {
      console.error('Error:', err);
    }
  };

  const handleUpdateTodo = async (todoData) => {
    try {
      const response = await todoService.updateTodo(editingTodo._id, todoData);
      setTodos(todos.map((todo) =>
        todo._id === editingTodo._id ? response.data : todo
      ));
      setEditingTodo(null);
    } catch (err) {
      console.error('Error:', err);
    }
  };

  const handleToggleTodo = async (id) => {
    try {
      const response = await todoService.toggleTodo(id);
      setTodos(todos.map((todo) =>
        todo._id === id ? response.data : todo
      ));
    } catch (err) {
      console.error('Error:', err);
    }
  };

  const handleDeleteTodo = async (id) => {
    if (window.confirm('¿Estás seguro de que deseas eliminar esta tarea?')) {
      try {
        await todoService.deleteTodo(id);
        setTodos(todos.filter((todo) => todo._id !== id));
      } catch (err) {
        console.error('Error:', err);
      }
    }
  };

  const handleEditTodo = (todo) => {
    setEditingTodo(todo);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleCancelEdit = () => {
    setEditingTodo(null);
  };

  const handleSubmit = (todoData) => {
    if (editingTodo) {
      handleUpdateTodo(todoData);
    } else {
      handleCreateTodo(todoData);
    }
  };

  return (
    <div className="App">
      <header className="app-header">
        <h1>To-Do List</h1>
        <p className="subtitle">Gestiona tus tareas de manera eficiente</p>
      </header>

      <main className="app-main">
        {error && (
          <div className="error-message">
            {error}
          </div>
        )}

        <div className="container">
          <TodoForm
            onSubmit={handleSubmit}
            editingTodo={editingTodo}
            onCancel={handleCancelEdit}
          />

          {loading ? (
            <div className="loading">Cargando tareas...</div>
          ) : (
            <TodoList
              todos={todos}
              onToggle={handleToggleTodo}
              onEdit={handleEditTodo}
              onDelete={handleDeleteTodo}
            />
          )}
        </div>
      </main>

      <footer className="app-footer">
        <p>Desarrollado por Joan Martínez | React + Node.js + MongoDB</p>
      </footer>
    </div>
  );
}

export default App;
